### ISSUE TITLE
Remove dropdown from team in navbar and change it to team and change photos of team ( with correct details) on home page.

### ISSUE THREAD

**Issue by SaurabhTiwari4093** [eDC-IIT-Delhi/website-2022#3]

**Comment by SaurabhTiwari4093** [comment]
Drop down wala to sahi se kar diya hai. Mai photos bhejta usko bhi update kar dena.

**Comment by SaurabhTiwari4093** [comment]
Drop down wala to shai dekh raha hai. Photos aur detail bhi update kardo.

**Comment by deenium** [comment]
Sir, would you provide the images of homepage, I'll update it
