### ISSUE TITLE
Remove drop down from becon in navbar and change it to Becon'22. Also correct  contact us button moving to right on click in navbar.

### ISSUE THREAD

**Issue by SaurabhTiwari4093** [eDC-IIT-Delhi/website-2022#4]

**Comment by ashish4arora** [comment]
*The contact button was earlier changing font to blue on active but that was the same as its background so I kept it white only. Please check for that

Separate issues still pertaining are: 
scrollTo Becon'22 is a bit off
Becon'22 doesn't highlight in the navbar when at it's section

**Comment by SaurabhTiwari4093** [comment]
Ye dono issue bhi sahi kar do.
